// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mangment.Models;

[PrimaryKey("StudentId", "CourseId")]
[Index("CourseId", Name = "IX_CourseStudents_CourseId")]
public partial class CourseStudent
{
    [Key]
    public int CourseId { get; set; }

    [Key]
    public int StudentId { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("CourseStudents")]
    public virtual Course Course { get; set; } = null!;

    [ForeignKey("StudentId")]
    [InverseProperty("CourseStudents")]
    public virtual Student Student { get; set; } = null!;
}