// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mangment.Models;

[Index("CourseId", Name = "IX_CouresSessions_CourseId")]
[Index("InstructorID", Name = "IX_CouresSessions_InstructorID")]
public partial class CouresSession
{
    [Key]
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public string? Title { get; set; }

    public int? CourseId { get; set; }

    public int? InstructorID { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("CouresSessions")]
    public virtual Course? Course { get; set; }

    [InverseProperty("CourseSession")]
    public virtual ICollection<CourseSessionAttandance> CourseSessionAttandances { get; set; } = new List<CourseSessionAttandance>();

    [ForeignKey("InstructorID")]
    [InverseProperty("CouresSessions")]
    public virtual Instructor? Instructor { get; set; }
}