// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mangment.Models;

[Index("CourseSessionID", Name = "IX_CourseSessionAttandances_CourseSessionID")]
[Index("StudentID", Name = "IX_CourseSessionAttandances_StudentID")]
public partial class CourseSessionAttandance
{
    [Key]
    public int Id { get; set; }

    public int? Grade { get; set; }

    public string? Notes { get; set; }

    public int? CourseSessionID { get; set; }

    public int? StudentID { get; set; }

    [ForeignKey("CourseSessionID")]
    [InverseProperty("CourseSessionAttandances")]
    public virtual CouresSession? CourseSession { get; set; }

    [ForeignKey("StudentID")]
    [InverseProperty("CourseSessionAttandances")]
    public virtual Student? Student { get; set; }
}