// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mangment.Models;

[Table("last transactions")]
public partial class last_transaction
{
    [Key]
    public int UserID { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? TransactionAmount { get; set; }
}