// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mangment.Models;

public partial class Student
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    public string? FName { get; set; }

    [StringLength(255)]
    public string? LName { get; set; }

    [StringLength(255)]
    public string? Phone { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<CourseSessionAttandance> CourseSessionAttandances { get; set; } = new List<CourseSessionAttandance>();

    [InverseProperty("Student")]
    public virtual ICollection<CourseStudent> CourseStudents { get; set; } = new List<CourseStudent>();
    [NotMapped] // EF Core should ignore this in the database
    public string FullName => $"{FName} {LName}";

    public override string ToString()
    {
        return $"{FullName}";
    }
}