// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using mangment.Context;
using mangment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace mangment.Context.Configurations
{
    public partial class daily_transactionConfiguration : IEntityTypeConfiguration<daily_transaction>
    {
        public void Configure(EntityTypeBuilder<daily_transaction> entity)
        {
            entity.HasKey(e => e.UserID).HasName("PK__daily tr__1788CCAC67410556");

            entity.Property(e => e.UserID).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<daily_transaction> entity);
    }
}
