// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using mangment.Context;
using mangment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace mangment.Context.Configurations
{
    public partial class last_transactionConfiguration : IEntityTypeConfiguration<last_transaction>
    {
        public void Configure(EntityTypeBuilder<last_transaction> entity)
        {
            entity.HasKey(e => e.UserID).HasName("PK__last tra__1788CCAC5323C1CC");

            entity.Property(e => e.UserID).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<last_transaction> entity);
    }
}
